[package]
name = "ferrumena"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
envy = "0.4.2"
reqwest = "0.13.2"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
